data:
  _trainProjects_:

    - proj_name: "2024-03-22_FW_Koenigshuegel.FwfProj"   # building
    - proj_name: "2024-04-05_FW_Westbahnhof_02.FwfProj"  # tunnel-bridge
    - proj_name: "2024-04-05_FW_Westbahnhof_03.FwfProj"  # tunnel-bridge
    - proj_name: "2024-04-05_FW_Westbahnhof_04.FwfProj"  # tunnel-bridge
    - proj_name: "2024-04-05_FW_Westbahnhof_05.FwfProj"  # building
    - proj_name: "2024-05-10_FW_RWTH_Zentrum_01.FwfProj" # building
    - proj_name: "2024-07-31_FW_Bruecke_Koenigstr.FwfProj" # bridge (steel+stone)
      bboxes: [0, 2]
    - proj_name: "2024-08-02_FW_Bruecke_A44_VerlautenheidenerStr.FwfProj" # bridge (concrete)
    - proj_name: "2024-08-02_FW_Bruecke_Deltourserb.FwfProj" # bridge (concrete)
    - proj_name: "2024-08-02_FW_Bruecke_Kasinostrasse.FwfProj" # bridge (concrete, steel, brick)
      bboxes: [1]
    - proj_name: "2024-08-02_FW_Bruecke_RotheErde.FwfProj" # bridge (steel)
    # - proj_name: "2024-08-02_FW_Bruecke_Rottstrasse.FwfProj" # bridge (concrete)

  _valProjects_:
    - proj_name: "2023-08-28_FW_EingangBauing.FwfProj" # building
    - proj_name: "2024-04-05_FW_Westbahnhof_01.FwfProj" # tunnel-bridge
    - proj_name: "2024-07-31_FW_Bruecke_Koenigstr.FwfProj" # bridge (steel+stone)
      bboxes: [1]
    - proj_name: "2024-08-02_FW_Bruecke_Kasinostrasse.FwfProj" # bridge (concrete, steel, brick)
      bboxes: [0]
    - proj_name: "2024-07-31_FW_Bruecke_Turmstr.FwfProj" # bridge (concrete/steel)
  _testProjects_:
    - proj_name: "2023-08-28_FW_EingangBauing.FwfProj" # building
    - proj_name: "2024-04-05_FW_Westbahnhof_01.FwfProj" # tunnel-bridge
    - proj_name: "2024-07-31_FW_Bruecke_Koenigstr.FwfProj" # bridge (steel+stone)
      bboxes: [1]
    - proj_name: "2024-08-02_FW_Bruecke_Kasinostrasse.FwfProj" # bridge (concrete, steel, brick)
      bboxes: [0]
    - proj_name: "2024-07-31_FW_Bruecke_Turmstr.FwfProj" # bridge (concrete/steel)

