experiment:
  title_suffix: "v203"
  description: "Based on v106, batch-4 now measures the effect of the training data volume"
general:
  device: 'cuda'
  batch_size : 1024
  weight_decay : 5e-4
  max_epochs : 25
  early_stopping_minDelta: 0.01
  num_workers: 4
data:
  # dataset_root : "D:\\Projekte\\GIA_220412_PCS\\02_Datasets\\FullWaveForm\\full_waveform_software\\FullWaveformParse_mass\\output\\FWF_Subsampled\\0.01" # work pc
  # dataset_root : "/media/hristo/DATA/Projekte/GIA_220412_PCS/02_Datasets/FullWaveForm/full_waveform_software/FullWaveformParse_mass/output/FWF_Aachen_labeled"
  dataset_root : "../../02_Datasets/FWF_Subsampled/0.01_simple/" # home pc
  split: "./config/batch_04/splits/v203-split.yaml"
  preprocessing:
    # Transforms
    _transformsTraining_:
      xyz:
        TransCenterXyz : {}
        TransZRotation : {}
        TransScaling: {}
        TransGaussianNoise : {mean: 0, std: 0.002}
      rgb:
        TransGaussianNoise : {mean: 0, std: 0.02}
        TransFeatureDropout : {dropout_prob : 0.1}
      wfm:
        TransSignalScaling : {}
      normals:
        TransGaussianNoise : {mean: 0, std: 0.05}
      incAngles:
        TransGaussianNoise : {mean: 0, std: 0.05}
        TransStandardize : {mean: 2.07, std: 0.38}
      distanceFromScanner:
        TransGaussianNoise: {mean: 12.13, std: 12.20}
    _transformsValidation_:
      xyz:
        TransCenterXyz : {}
        # TransZRotation : {}
        # TransScaling: {}
        # TransGaussianNoise : {mean: 0, std: 0.002}
      # rgb:
        # TransGaussianNoise : {mean: 0, std: 0.02}
        # TransFeatureDropout : {dropout_prob : 0.1}
      # wfm:
        # TransSignalScaling : {}
      # normals:
        # TransGaussianNoise : {mean: 0, std: 0.05}
      incAngles:
        # TransGaussianNoise : {mean: 0, std: 0.05}
        TransStandardize : {mean: 2.07, std: 0.38}
      distanceFromScanner:
        TransStandardize: {mean: 12.13, std: 12.20}
    subsampling:
  # Dataset
  scalar_input_fields:
    - 'xyz'
    - 'rgb'
    - 'riegl_feats'
    - 'geom_feats'
    - 'normals'
    - 'incAngles'
    - 'distanceFromScanner'
  fw_input_field: True
  label_names:
    # - 'labels_0'
    # - 'labels_1'
    # - 'labels_2'
    - 'labels_3'

  weighted_random_subsample: True
  query_grid_size: 0.15
  subsample_on_gpu: True
  num_neib_normalsComputation: 20
  num_neib_featureExtraction: 128
model:
  use_global_constraint: False
  dropout_prob: 0.3
  ignore_waveform : False
  ignore_neibors : False
testing:
  query_grid_size: 0.03
  batch_size: 1024


